# This file controls the settings for your Quarto template from www.marvinschmitt.com
# website settings
website:
  title: "Amber Fredenburg"
  description: "Ecologist and Wild Bee Researcher"
  image: img/IMG_5379.JPG
  favicon: img/Beetiny.png

 # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/Bee.png

    left:
      - text: "Projects"
        href: "projects/index.qmd"
      - text: "Publications"
        href: "Publications/index.qmd"
      - text: "Mentoring"
        href: "Mentoring/index.qmd"
      - text: "CV"
        href: "cv/index.qmd"

    right:
      - icon: linkedin
        href: "https://www.linkedin.com/in/amber-fredenburg-133319157/"
      - icon: envelope
        text: "Personal Email"
        href: "mailto:afredenburg95@gmail.com"
      - icon: envelope
        text: "OSU Email"
        href: "mailto:fredenburg.7@buckeyemail.osu.com"

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true